# Generated by Django 5.0.1 on 2024-01-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_learner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercutsom',
            old_name='is_admin',
            new_name='is_lectuer',
        ),
    ]
