# Generated by Django 5.0.1 on 2024-01-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='attempt_timestamp',
        ),
        migrations.AddField(
            model_name='user_answer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
