# Generated by Django 5.0.1 on 2024-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_answer_attempt_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='user_answer',
            name='marks',
        ),
        migrations.AddField(
            model_name='user_answer',
            name='user_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='User Mark'),
        ),
    ]
