# Generated by Django 5.0.1 on 2024-01-19 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_answer_attempt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='attempt_number',
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_answer',
            name='quiz_attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.quizattempt'),
        ),
    ]
