# Generated by Django 5.0.1 on 2024-01-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_user_answer_attempt_number_quizattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='quiz_attempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
