# Generated by Django 5.0.1 on 2024-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_usercutsom_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercutsom',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercutsom',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
