# Generated by Django 5.0.1 on 2024-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_userquizprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=300, verbose_name='Time Limit (seconds)'),
        ),
    ]
