# Generated by Django 5.0.1 on 2024-01-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_quiz_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercutsom',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
