# Generated by Django 5.0.1 on 2024-01-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_answer_attempt_number_quizattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='user_answer',
            name='attempt_number',
        ),
    ]
