# Generated by Django 5.0.1 on 2024-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_quizattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_answer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
