# Generated by Django 5.0.1 on 2024-01-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_quizattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='attempt_number',
        ),
    ]
