# Generated by Django 5.0.1 on 2024-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_user_answer_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
