# Generated by Django 5.0.1 on 2024-01-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_user_answer_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
