# Generated by Django 5.0.1 on 2024-01-31 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_answer_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercutsom',
            name='created_token',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercutsom',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
