# Generated by Django 5.0.1 on 2024-02-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_usercutsom_created_token_usercutsom_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='total_mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
